/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/interviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Interview
         * @description RI-38. Una entrevista nueva con su primera pregunta.
         */
        post: operations["create_interview_interviews_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interviews/{interview_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Interview
         * @description RI-40. El mismo estado que RI-39, para reanudar.
         */
        get: operations["get_interview_interviews__interview_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interviews/{interview_id}/turns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Turn
         * @description RI-39. Respuesta, texto libre, ediciones y decisiones sobre hechos propuestos.
         */
        post: operations["send_turn_interviews__interview_id__turns_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/novels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Novels
         * @description RI-37. Las novelas del directorio de tiradas, con su estado y sus versiones.
         *
         *     Vive aqui y no en `canon/` porque el estado de la tirada es del Orquestador.
         */
        get: operations["list_novels_novels_get"];
        put?: never;
        /**
         * Create
         * @description RI-01. Carga el brief. Es la unica escritura que la API provoca.
         */
        post: operations["create_novels_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/novels/{novel_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get State
         * @description RI-03. Capitulo y escena en curso, congelados, cuarentenas, cierre.
         */
        get: operations["get_state_novels__novel_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/novels/{novel_id}/change-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Change Requests
         * @description RI-48. Todas las solicitudes con su estado.
         */
        get: operations["list_change_requests_novels__novel_id__change_requests_get"];
        put?: never;
        /**
         * Create Change Request
         * @description RI-47. Interpreta en la misma llamada (D-82) y deja la solicitud en cola o rechazada.
         *
         *     Con la tirada en marcha, el bucle la aplica tras el siguiente capitulo
         *     congelado. Sin tirada, el Orquestador la aplica enseguida en su hilo (D-77).
         */
        post: operations["create_change_request_novels__novel_id__change_requests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/novels/{novel_id}/change-requests/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Change Request
         * @description RI-49. Estado, interpretacion y, si se aplico, la version que produjo.
         */
        get: operations["get_change_request_novels__novel_id__change_requests__request_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/novels/{novel_id}/chapters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Chapters
         * @description RI-04. Solo capitulos congelados: son los unicos que estan en el indice.
         */
        get: operations["list_chapters_novels__novel_id__chapters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/novels/{novel_id}/chapters/{number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Chapter
         * @description RI-05. La prosa de un capitulo congelado.
         */
        get: operations["get_chapter_novels__novel_id__chapters__number__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/novels/{novel_id}/chapters/{number}/verdict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Verdict
         * @description RI-29. El veredicto del Jurado sobre un capitulo congelado.
         */
        get: operations["get_verdict_novels__novel_id__chapters__number__verdict_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/novels/{novel_id}/debt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Debt
         * @description RI-07. Setups abiertos y compromisos sin plantar.
         */
        get: operations["read_debt_novels__novel_id__debt_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/novels/{novel_id}/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Entities
         * @description RI-45. Personajes, lugares, instituciones y objetos, con los capitulos donde aparecen.
         */
        get: operations["list_entities_novels__novel_id__entities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/novels/{novel_id}/entities/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Entity
         * @description RI-46. La ficha: compacta, hechos con procedencia, relaciones vigentes y apariciones.
         */
        get: operations["get_entity_novels__novel_id__entities__entity_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/novels/{novel_id}/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Health */
        get: operations["get_health_novels__novel_id__health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/novels/{novel_id}/retcons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Retcons
         * @description RI-31. Los retcons aplicados, con la regla que los admitio.
         */
        get: operations["list_retcons_novels__novel_id__retcons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/novels/{novel_id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Run
         * @description RI-02. Arranca la tirada. Idempotente: si ya corre, devuelve el estado.
         */
        post: operations["start_run_novels__novel_id__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/novels/{novel_id}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get State
         * @description RI-06. El estado del mundo en un instante.
         *
         *     El instante es obligatorio: un estado sin instante no significa nada en un
         *     sistema donde todo tiene vigencia.
         *
         *     El formato se declara **en el contrato** y no solo en el validador. Mientras
         *     vivio solo en el codigo, el esquema prometia aceptar cualquier texto y la
         *     ruta rechazaba casi todos: un cliente generado desde ese contrato habria
         *     enviado basura convencido de que era valida. Lo encontro la comprobacion
         *     generativa, que es para lo que esta.
         */
        get: operations["get_state_novels__novel_id__state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/novels/{novel_id}/style": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Style
         * @description RI-30. Huella de referencia y la de cada capitulo, con su desviacion.
         */
        get: operations["get_style_novels__novel_id__style_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/novels/{novel_id}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Trace
         * @description RI-27, RI-65. Los registros de la traza, en orden de escritura, y donde se rompe.
         */
        get: operations["get_trace_novels__novel_id__trace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/novels/{novel_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Versions
         * @description RI-42. Versiones del manuscrito (PRO-08): la 1 es la tirada, cada enmienda una mas.
         */
        get: operations["list_versions_novels__novel_id__versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/novels/{novel_id}/versions/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Manifest
         * @description RI-43. Portada e indice de una version, con los capitulos cambiados marcados.
         */
        get: operations["get_manifest_novels__novel_id__versions__version__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/novels/{novel_id}/versions/{version}/chapters/{number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Chapter At
         * @description RI-44. Un capitulo tal como estaba en una version, con sus escenas cambiadas marcadas.
         */
        get: operations["get_chapter_at_novels__novel_id__versions__version__chapters__number__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Appearance */
        Appearance: {
            /** Chapter */
            chapter: number;
            /**
             * Roles
             * @description pov, place, cast
             */
            roles: string[];
            /** Scene Id */
            scene_id: string;
            /** Scene Number */
            scene_number: number;
        };
        /**
         * Brief
         * @description El encargo de la obra.
         *
         *     `start` es el instante en que arranca el mundo: todo lo que el brief
         *     establece es cierto desde ahi, y nada anterior existe.
         *
         *     Lo que va despues de `word_tolerance` lo trae la entrevista (RF-200). Es
         *     opcional para que un brief escrito a mano, sin destinatario, siga valiendo.
         */
        Brief: {
            /**
             * Dedication
             * @default
             */
            dedication?: string;
            /** Entities */
            entities: components["schemas"]["BriefEntity"][];
            /** Forbidden Themes */
            forbidden_themes?: string[];
            /** Forbidden Words */
            forbidden_words?: string[];
            /**
             * Genre
             * @default
             */
            genre?: string;
            /**
             * @description T53. Perfil de extension: novela, o prueba para una obra minima
             * @default novela
             */
            length_profile?: components["schemas"]["LengthProfileName"];
            /**
             * Origin Interview
             * @description RF-249: la entrevista de la que sale el brief, si sale de una
             */
            origin_interview?: string | null;
            recipient?: components["schemas"]["Recipient"] | null;
            /** Relations */
            relations?: components["schemas"]["BriefRelation"][];
            /**
             * Rulebook
             * @description DEP-02, vacio si no es deportiva
             * @default
             */
            rulebook?: string;
            start: components["schemas"]["WorldTime"];
            /**
             * Style Guide
             * @description POE-06
             */
            style_guide: string;
            /** Target Words */
            target_words: number;
            /** Title */
            title: string;
            /**
             * Tone
             * @default
             */
            tone?: string;
            /**
             * Word Tolerance
             * @default 0.1
             */
            word_tolerance?: number;
        };
        /** BriefEntity */
        BriefEntity: {
            /** Aliases */
            aliases?: string[];
            /** Attributes */
            attributes?: [
                string,
                string
            ][];
            /** Competences */
            competences?: [
                string,
                string
            ][];
            /** Id */
            id: string;
            /**
             * Kind
             * @description person | place | institution | object
             */
            kind: string;
            /** Name */
            name: string;
        };
        /** BriefRelation */
        BriefRelation: {
            /** Kind */
            kind: string;
            /** Source */
            source: string;
            /** Target */
            target: string;
        };
        /**
         * ChangeRequest
         * @description RI-49. Una solicitud y lo que el sistema hizo con ella.
         */
        ChangeRequest: {
            /** Anchor */
            anchor: {
                [key: string]: string | number;
            };
            /** Changed Chapters */
            changed_chapters: number[];
            /** Created At */
            created_at: string;
            interpretation: components["schemas"]["Interpretation"] | null;
            /** Reason */
            reason: string;
            /** Request Id */
            request_id: number;
            /** Status */
            status: string;
            /** Text */
            text: string;
            /** Updated At */
            updated_at: string;
            /** Version */
            version: number | null;
        };
        /**
         * ChangeRequestIn
         * @description RI-47. La peticion y su ancla: un fragmento de la lectura o un hecho de la ficha.
         */
        ChangeRequestIn: {
            /** Anchor */
            anchor: components["schemas"]["FragmentAnchor"] | components["schemas"]["FactAnchor"];
            /**
             * Text
             * @description Texto no confiable
             */
            text: string;
        };
        /** ChangeRequestList */
        ChangeRequestList: {
            /** Requests */
            requests: components["schemas"]["ChangeRequest"][];
        };
        /** ChapterAtVersion */
        ChapterAtVersion: {
            /** Chapter */
            chapter: number;
            /** Scenes */
            scenes: components["schemas"]["SceneAt"][];
            /** Version */
            version: number;
        };
        /** ChapterEntry */
        ChapterEntry: {
            /** Changed */
            changed: boolean;
            /** Number */
            number: number;
            /**
             * Title
             * @description Nulo mientras la escaleta no tenga almacen (D-79)
             */
            title: string | null;
            /** Words */
            words: number;
        };
        /** ChapterHealth */
        ChapterHealth: {
            /** Alarms */
            alarms: number;
            /** Chapter */
            chapter: number;
            /** Signals */
            signals: components["schemas"]["MetricRow"][];
        };
        /** ChapterList */
        ChapterList: {
            /** Chapters */
            chapters: components["schemas"]["ChapterSummary"][];
        };
        /** ChapterProse */
        ChapterProse: {
            /** Chapter */
            chapter: number;
            /** Scenes */
            scenes: components["schemas"]["SceneProse"][];
        };
        /** ChapterSummary */
        ChapterSummary: {
            /** Chapter */
            chapter: number;
            /**
             * Ends At
             * @description Instante de mundo de su ultima escena, ISO 8601
             */
            ends_at: string;
            /**
             * Ends Seq
             * @description Desempate de ese instante
             */
            ends_seq: number;
            /** Scenes */
            scenes: number;
            /** Words */
            words: number;
        };
        /** ChapterVerdict */
        ChapterVerdict: {
            /** Chapter */
            chapter: number;
            /** Dimensions */
            dimensions: components["schemas"]["DimensionOut"][];
        };
        /**
         * Contradiction
         * @description Dos campos que no pueden ser ciertos a la vez, y la regla que lo dice.
         */
        Contradiction: {
            /** Fields */
            fields: [
                string,
                string
            ];
            /** Message */
            message: string;
            /** Rule */
            rule: string;
        };
        /**
         * Debt
         * @description CAN-08. La deuda narrativa vigente.
         */
        Debt: {
            /**
             * Open Setups
             * @description Plantados y sin cobrar. Esto es lo que se debe
             */
            open_setups: components["schemas"]["SetupStatus"][];
            /** Paid */
            paid?: components["schemas"]["SetupStatus"][];
            /**
             * Planned
             * @description Ni plantados aun. No son deuda todavia, pero son compromiso
             */
            planned: components["schemas"]["SetupStatus"][];
        };
        /** DimensionOut */
        DimensionOut: {
            /** Dimension */
            dimension: string;
            /**
             * Discarded Instances
             * @description Instancias del Jurado sin puntuacion anclada en esta dimension (RF-129)
             * @default []
             */
            discarded_instances?: string[];
            /** Dispersion */
            dispersion: number;
            /** Level */
            level: number | null;
            /** Scores */
            scores: components["schemas"]["ScoreOut"][];
            /** Valid */
            valid: boolean;
        };
        /**
         * Draft
         * @description RF-169 del frontend: lo que el panel muestra. Vacio al empezar.
         */
        Draft: {
            /**
             * Answered
             * @default []
             */
            answered?: ("title" | "recipient.name" | "recipient.age" | "recipient.birth_date" | "recipient.role" | "premise" | "genre" | "tone" | "target_words" | "start" | "dedication" | "recipient.traits" | "recipient.memories" | "forbidden_words" | "forbidden_themes")[];
            /**
             * Dedication
             * @default
             */
            dedication?: string;
            /**
             * Entities
             * @default []
             */
            entities?: components["schemas"]["ExtraEntity"][];
            /**
             * Forbidden Themes
             * @default []
             */
            forbidden_themes?: string[];
            /**
             * Forbidden Words
             * @default []
             */
            forbidden_words?: string[];
            /**
             * Genre
             * @default
             */
            genre?: string;
            /**
             * Premise
             * @default
             */
            premise?: string;
            /** Recipient Age */
            recipient_age?: number | null;
            /**
             * Recipient Birth Date
             * @default
             */
            recipient_birth_date?: string;
            /**
             * Recipient Memories
             * @default []
             */
            recipient_memories?: string[];
            /**
             * Recipient Name
             * @default
             */
            recipient_name?: string;
            /**
             * Recipient Role
             * @default
             */
            recipient_role?: string;
            /**
             * Recipient Traits
             * @default []
             */
            recipient_traits?: string[];
            /**
             * Start
             * @default
             */
            start?: string;
            /** Target Words */
            target_words?: number | null;
            /**
             * Title
             * @default
             */
            title?: string;
            /**
             * Tone
             * @default
             */
            tone?: string;
        };
        /**
         * EntityCard
         * @description Ficha de entidad. CTX-05 en su forma compacta.
         *
         *     Compacta y completa se diferencian en cuanto traen, no en su forma: seis
         *     compactas caben en 1.600 tokens y una completa en 800 (RF-09).
         */
        EntityCard: {
            /** Aliases */
            aliases?: string[];
            /** Attributes */
            attributes?: [
                string,
                string
            ][];
            /** Competences */
            competences?: [
                string,
                string
            ][];
            /** Entity Id */
            entity_id: string;
            /** Kind */
            kind: string;
            /** Name */
            name: string;
        };
        /**
         * EntityFile
         * @description RI-46. La ficha de una entidad.
         */
        EntityFile: {
            /** Appearances */
            appearances: components["schemas"]["Appearance"][];
            /** @description Ficha compacta, CTX-05 */
            card: components["schemas"]["EntityCard"];
            entity: components["schemas"]["EntitySummary"];
            /** Facts */
            facts: components["schemas"]["Fact"][];
            /** Relations */
            relations: components["schemas"]["EntityRelation"][];
        };
        /** EntityList */
        EntityList: {
            /** Entities */
            entities: components["schemas"]["EntitySummary"][];
        };
        /** EntityRelation */
        EntityRelation: {
            /**
             * Direction
             * @description out si la entidad es el origen, in si es el destino
             */
            direction: string;
            /** Kind */
            kind: string;
            /** Other Id */
            other_id: string;
            /** Other Name */
            other_name: string;
            /** Valid From */
            valid_from: string;
            /** Valid To */
            valid_to?: string | null;
        };
        /** EntitySummary */
        EntitySummary: {
            /** Aliases */
            aliases: string[];
            /**
             * Chapters
             * @description Capitulos congelados donde aparece
             */
            chapters: number[];
            /** Entity Id */
            entity_id: string;
            /** Kind */
            kind: string;
            /** Name */
            name: string;
        };
        /**
         * ExtraEntity
         * @description Un personaje o un lugar que entro al aceptar un hecho propuesto (RF-218).
         */
        ExtraEntity: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "person" | "place";
            /** Name */
            name: string;
            /**
             * Note
             * @default
             */
            note?: string;
        };
        /** Fact */
        Fact: {
            /** Attribute */
            attribute: string;
            /**
             * Provenance
             * @description MET-09: brief, prose, derived o arbitration
             */
            provenance: string;
            /** Valid From */
            valid_from: string;
            /** Value */
            value: string;
        };
        /**
         * FactAnchor
         * @description Un hecho de la ficha: entidad y atributo.
         */
        FactAnchor: {
            /** Attribute */
            attribute: string;
            /** Entity Id */
            entity_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "fact";
        };
        /**
         * FieldEdit
         * @description RF-214. Un campo por nombre; los de lista, separados por comas.
         */
        FieldEdit: {
            /**
             * Field
             * @enum {string}
             */
            field: "title" | "recipient.name" | "recipient.age" | "recipient.birth_date" | "recipient.role" | "premise" | "genre" | "tone" | "target_words" | "start" | "dedication" | "recipient.traits" | "recipient.memories" | "forbidden_words" | "forbidden_themes";
            /** Value */
            value: string;
        };
        /**
         * FingerprintRow
         * @description RD-21. La huella de un capitulo congelado.
         */
        FingerprintRow: {
            /** Adj Noun Ratio */
            adj_noun_ratio: number;
            /** Chapter */
            chapter: number;
            /** Deviation */
            deviation?: number | null;
            /**
             * Is Reference
             * @default false
             */
            is_reference?: boolean;
            /** Lexical Richness */
            lexical_richness: number;
            /** Mean Sentence Len */
            mean_sentence_len: number;
            /** Top Ngrams */
            top_ngrams: string[];
            /** Var Sentence Len */
            var_sentence_len: number;
        };
        /**
         * FragmentAnchor
         * @description Una seleccion del lector: la cita literal, sin recortar ni normalizar (RD-30 del frontend).
         */
        FragmentAnchor: {
            /** Chapter */
            chapter: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "fragment";
            /** Quote */
            quote: string;
            /** Scene Id */
            scene_id: string;
            /** Version */
            version: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Chapters */
            chapters: components["schemas"]["ChapterHealth"][];
            /** Novel Id */
            novel_id: string;
        };
        /**
         * Interpretation
         * @description Lo que el sistema entendio (RI-52, RI-67).
         *
         *     Un `fact` es exactamente una entidad y un atributo. Un `forbid` es un termino
         *     que no debe aparecer en la novela (RF-256): entidad, atributo y valores van
         *     vacios, y el termino en `term`.
         */
        Interpretation: {
            /** Attribute */
            attribute: string;
            /** Entity Id */
            entity_id: string;
            /**
             * Kind
             * @description `fact` o `forbid` (RI-67)
             * @default fact
             * @enum {string}
             */
            kind?: "fact" | "forbid";
            /** New Value */
            new_value: string;
            /** Previous Value */
            previous_value: string;
            /**
             * Term
             * @description Nulo salvo en `forbid`
             */
            term?: string | null;
        };
        /**
         * InterviewState
         * @description RI-39, RI-40 del frontend.
         */
        InterviewState: {
            /** @description En la forma de RI-01, solo si el brief esta completo */
            brief: components["schemas"]["Brief"] | null;
            /** Complete */
            complete: boolean;
            /** Contradictions */
            contradictions: components["schemas"]["Contradiction"][];
            /**
             * Discarded Quotes
             * @description Citas descartadas por no aparecer literales
             */
            discarded_quotes: number;
            draft: components["schemas"]["Draft"];
            /** Interview Id */
            interview_id: string;
            /** Messages */
            messages: components["schemas"]["Message"][];
            /** Missing */
            missing: components["schemas"]["Missing"][];
            /**
             * Novel Id
             * @description Identificador sugerido para RI-01 (D-81)
             */
            novel_id: string | null;
            /** Proposed */
            proposed: components["schemas"]["ProposedFact"][];
            question: components["schemas"]["Question"] | null;
        };
        JsonValue: unknown;
        /**
         * LengthProfileName
         * @enum {string}
         */
        LengthProfileName: "novela" | "prueba";
        /**
         * Manifest
         * @description RI-43. Portada e indice de una version.
         */
        Manifest: {
            /** Chapters */
            chapters: components["schemas"]["ChapterEntry"][];
            /** Current */
            current: boolean;
            /** Dedication */
            dedication: string;
            /** Recipient Name */
            recipient_name: string;
            /** Title */
            title: string;
            /** Version */
            version: number;
        };
        /** Message */
        Message: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "question" | "answer" | "free_text" | "note";
            /**
             * Role
             * @enum {string}
             */
            role: "interviewer" | "person";
            /** Text */
            text: string;
        };
        /**
         * MetricRow
         * @description RD-22. Una senal de `architecture.md` §11 para un capitulo.
         */
        MetricRow: {
            /** Chapter */
            chapter: number;
            /** Signal */
            signal: string;
            /** State */
            state: string;
            /** Threshold */
            threshold: string;
            /** Value */
            value: number | null;
        };
        /** Missing */
        Missing: {
            /**
             * Field
             * @enum {string}
             */
            field: "title" | "recipient.name" | "recipient.age" | "recipient.birth_date" | "recipient.role" | "premise" | "genre" | "tone" | "target_words" | "start" | "dedication" | "recipient.traits" | "recipient.memories" | "forbidden_words" | "forbidden_themes";
            /** Label */
            label: string;
        };
        /** NovelCreated */
        NovelCreated: {
            /**
             * Events Loaded
             * @description Hechos que el brief aporto al canon
             */
            events_loaded: number;
            /** Novel Id */
            novel_id: string;
        };
        /** NovelEntry */
        NovelEntry: {
            /** Novel Id */
            novel_id: string;
            state: components["schemas"]["RunState"];
            /** Title */
            title: string;
            /** Versions */
            versions: number;
        };
        /** NovelList */
        NovelList: {
            /** Novels */
            novels: components["schemas"]["NovelEntry"][];
        };
        /**
         * ProposedFact
         * @description RF-174 del frontend: un hecho sacado del texto libre, con su cita.
         */
        ProposedFact: {
            /** Fact Id */
            fact_id: string;
            /** Quote */
            quote: string;
            /**
             * Status
             * @default proposed
             * @enum {string}
             */
            status?: "proposed" | "accepted" | "discarded";
            /**
             * Target
             * @enum {string}
             */
            target: "recipient.traits" | "recipient.memories" | "entity.person" | "entity.place";
            /** Value */
            value: string;
        };
        /** Question */
        Question: {
            /**
             * Field
             * @enum {string}
             */
            field: "title" | "recipient.name" | "recipient.age" | "recipient.birth_date" | "recipient.role" | "premise" | "genre" | "tone" | "target_words" | "start" | "dedication" | "recipient.traits" | "recipient.memories" | "forbidden_words" | "forbidden_themes";
            /** Text */
            text: string;
        };
        /**
         * Recipient
         * @description RF-200, RD-42. Para quien es la novela: una entidad del brief, con lo que la entrevista recogio.
         *
         *     `birth_date` y `optional` son opcionales para que los briefs anteriores
         *     sigan valiendo. `optional` es el subconjunto de rasgos y recuerdos que no
         *     son obligatorios (RF-260): lo que no esta en `traits` ni en `memories` no
         *     puede ser opcional, porque no hay nada que eximir.
         */
        Recipient: {
            /** Age */
            age: number;
            /**
             * Birth Date
             * @description ISO 8601, AAAA-MM-DD. RF-249: la entrevista la pregunta tras la edad
             */
            birth_date?: string | null;
            /** Entity Id */
            entity_id: string;
            /** Memories */
            memories?: string[];
            /**
             * Optional
             * @description Rasgos y recuerdos que no son obligatorios (RD-42)
             */
            optional?: string[];
            /**
             * Role
             * @description Papel en la historia
             */
            role: string;
            /** Traits */
            traits?: string[];
        };
        /**
         * Relation
         * @description Una arista del grafo de entidades (MET-03), con su vigencia (MET-07).
         */
        Relation: {
            /** Kind */
            kind: string;
            /** Source Id */
            source_id: string;
            /** Target Id */
            target_id: string;
            /** Valid From */
            valid_from: string;
            /** Valid To */
            valid_to?: string | null;
        };
        /** RetconEntry */
        RetconEntry: {
            /** Chapter Origin */
            chapter_origin: number;
            /** Fact Key */
            fact_key: string;
            /** New Value */
            new_value: string;
            /** Previous Value */
            previous_value: string;
            /** Refrozen Scenes */
            refrozen_scenes: string[];
            /** Rule */
            rule: string;
        };
        /** RetconList */
        RetconList: {
            /** Retcons */
            retcons: components["schemas"]["RetconEntry"][];
        };
        /**
         * RunState
         * @description RI-03. El estado de la tirada, solo lo que un lector puede ver.
         */
        RunState: {
            /** Chapter In Progress */
            chapter_in_progress?: number | null;
            /**
             * Closed
             * @description `None` mientras la tirada no ha terminado
             */
            closed?: boolean | null;
            /**
             * Error
             * @default
             */
            error?: string;
            /** Frozen Chapters */
            frozen_chapters: number;
            /** Last Closed Scene */
            last_closed_scene?: number | null;
            /** Novel Id */
            novel_id: string;
            /**
             * Quarantines
             * @description Veces que un capitulo se rehizo entero
             */
            quarantines: number;
            /**
             * Reason
             * @default
             */
            reason?: string;
            /** Running */
            running: boolean;
        };
        /**
         * SceneAt
         * @description RI-44. Una escena tal como estaba en una version.
         */
        SceneAt: {
            /**
             * Changed
             * @description Reescrita en esta version respecto a la anterior
             */
            changed: boolean;
            /** Pov */
            pov: string;
            /** Scene Id */
            scene_id: string;
            /** Scene Number */
            scene_number: number;
            /** Text */
            text: string;
        };
        /** SceneProse */
        SceneProse: {
            /** Pov */
            pov: string;
            /** Scene Number */
            scene_number: number;
            /** Text */
            text: string;
        };
        /** ScoreOut */
        ScoreOut: {
            /** Instance */
            instance: string;
            /** Offset */
            offset: number;
            /** Quote */
            quote: string;
            /** Scene Id */
            scene_id: string;
            /** Score */
            score: number;
            /** Seed */
            seed: number;
        };
        /**
         * SetupState
         * @description Estado de una promesa.
         *
         *     `PLANTED` cuando la escena que la planta esta congelada; `PAID` cuando lo
         *     esta la que la cobra. **Planificar no es plantar**: mientras las dos escenas
         *     sigan sin escribirse, la promesa esta prevista y no abierta, porque una
         *     promesa que el lector no ha leido todavia no debe nada.
         * @enum {string}
         */
        SetupState: "planificado" | "plantado" | "cobrado";
        /** SetupStatus */
        SetupStatus: {
            /** Description */
            description: string;
            /** Id */
            id: string;
            /** Payoff Chapter */
            payoff_chapter?: number | null;
            /** Payoff Scene */
            payoff_scene: string;
            /** Planted Chapter */
            planted_chapter?: number | null;
            /** Planted Scene */
            planted_scene: string;
            state: components["schemas"]["SetupState"];
        };
        /** StyleReport */
        StyleReport: {
            /** Chapters */
            chapters: components["schemas"]["FingerprintRow"][];
            /** Novel Id */
            novel_id: string;
        };
        /** TracePage */
        TracePage: {
            /**
             * Chain Broken At
             * @description Linea, desde 1, del primer registro cuya cadena de hashes no verifica; nulo si esta entera (RI-65, RF-253)
             */
            chain_broken_at?: number | null;
            /** Novel Id */
            novel_id: string;
            /** Records */
            records: components["schemas"]["TraceRecord"][];
        };
        /**
         * TraceRecord
         * @description Una linea de la traza.
         */
        TraceRecord: {
            /**
             * At
             * @description Instante real, ISO 8601 UTC
             */
            at: string;
            /** Fields */
            fields?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * Kind
             * @description call, admission, retry, defect, arbitration, ...
             */
            kind: string;
            /**
             * Prev Hash
             * @description sha256 del JSON canonico del registro anterior; vacio en el primero (RD-45)
             * @default
             */
            prev_hash?: string;
            /**
             * Seq
             * @description Orden de escritura dentro de la tirada
             */
            seq: number;
        };
        /**
         * TurnIn
         * @description RI-39. Todo opcional: un turno puede traer cualquier combinacion.
         */
        TurnIn: {
            /**
             * Accept
             * @default []
             */
            accept?: string[];
            /** Answer */
            answer?: string | null;
            /**
             * Discard
             * @default []
             */
            discard?: string[];
            /**
             * Edits
             * @default []
             */
            edits?: components["schemas"]["FieldEdit"][];
            /**
             * Free Text
             * @description Texto no confiable: una anecdota, una carta. Nunca instruye al sistema
             */
            free_text?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VersionInfo
         * @description RI-42. Una version del manuscrito (PRO-08).
         */
        VersionInfo: {
            /**
             * Cause
             * @description Solicitud que la produjo; nula en la 1
             */
            cause: number | null;
            /**
             * Changed Chapters
             * @description Capitulos cambiados respecto a la anterior
             */
            changed_chapters: number[];
            /**
             * Created At
             * @description Nulo en la 1: nace con la tirada
             */
            created_at: string | null;
            /** Current */
            current: boolean;
            /** Number */
            number: number;
        };
        /** VersionList */
        VersionList: {
            /** Versions */
            versions: components["schemas"]["VersionInfo"][];
        };
        /**
         * WorldState
         * @description MUN-10. Estado del mundo en un instante: fichas y relaciones vigentes.
         *
         *     Las relaciones no entran en ningun paquete de contexto: los agentes leen
         *     `cards`. Estan aqui porque MUN-10 las incluye y porque es de donde el grafo
         *     del frontend las lee mientras no exista su ruta propia.
         */
        WorldState: {
            at: components["schemas"]["WorldTime"];
            /** Cards */
            cards: components["schemas"]["EntityCard"][];
            /** Relations */
            relations?: components["schemas"]["Relation"][];
        };
        /**
         * WorldTime
         * @description MUN-05. Instante de mundo.
         *
         *     ISO 8601 mas `seq` de desempate (D-07). Se ordena por la tupla
         *     `(stamp, seq)`, que ordena lexicograficamente igual que cronologicamente:
         *     por eso el formato es fijo y se valida.
         *
         *     Estricto con los campos de mas (RF-248): es parte del brief --su `start`--
         *     y un `{"stamp": ..., "hora": ...}` que se aceptara en silencio perderia la
         *     hora sin que nadie lo supiera.
         */
        WorldTime: {
            /**
             * Seq
             * @description Desempate dentro del mismo instante
             * @default 0
             */
            seq?: number;
            /**
             * Stamp
             * @description ISO 8601: YYYY-MM-DD, opcionalmente con hora
             */
            stamp: string;
        };
        /** ErrorDetail */
        brief__routes__ErrorDetail: {
            /** Detail */
            detail: string;
        };
        /**
         * ErrorDetail
         * @description Cuerpo de todo error de esta API.
         *
         *     Se declara porque un contrato que dice "puede devolver 404" sin decir con
         *     que forma deja al cliente generado adivinando, que es la mitad del problema
         *     que el contrato existe para quitar.
         */
        canon__routes__ErrorDetail: {
            /** Detail */
            detail: string;
        };
        /** ErrorDetail */
        orchestration__routes__ErrorDetail: {
            /** Detail */
            detail: string;
        };
        /** ErrorDetail */
        planning__routes__ErrorDetail: {
            /** Detail */
            detail: string;
        };
        /** ErrorDetail */
        supervision__routes__ErrorDetail: {
            /** Detail */
            detail: string;
        };
        /** ErrorDetail */
        verification__routes__ErrorDetail: {
            /** Detail */
            detail: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_interview_interviews_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewState"];
                };
            };
        };
    };
    get_interview_interviews__interview_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador de la entrevista */
                interview_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewState"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["brief__routes__ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_turn_interviews__interview_id__turns_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador de la entrevista */
                interview_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TurnIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewState"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["brief__routes__ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_novels_novels_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NovelList"];
                };
            };
        };
    };
    create_novels_post: {
        parameters: {
            query: {
                /** @description Identificador de la novela */
                novel_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Brief"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NovelCreated"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["canon__routes__ErrorDetail"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["canon__routes__ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_state_novels__novel_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador de la novela */
                novel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunState"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["orchestration__routes__ErrorDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["orchestration__routes__ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_change_requests_novels__novel_id__change_requests_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador de la novela */
                novel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeRequestList"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["orchestration__routes__ErrorDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["orchestration__routes__ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_change_request_novels__novel_id__change_requests_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador de la novela */
                novel_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeRequestIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeRequest"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["orchestration__routes__ErrorDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["orchestration__routes__ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_change_request_novels__novel_id__change_requests__request_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador de la novela */
                novel_id: string;
                request_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeRequest"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["orchestration__routes__ErrorDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["orchestration__routes__ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_chapters_novels__novel_id__chapters_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador de la novela */
                novel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterList"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["canon__routes__ErrorDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["canon__routes__ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chapter_novels__novel_id__chapters__number__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador de la novela */
                novel_id: string;
                number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterProse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["canon__routes__ErrorDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["canon__routes__ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_verdict_novels__novel_id__chapters__number__verdict_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador de la novela */
                novel_id: string;
                number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterVerdict"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["verification__routes__ErrorDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["verification__routes__ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_debt_novels__novel_id__debt_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                novel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Debt"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["planning__routes__ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_entities_novels__novel_id__entities_get: {
        parameters: {
            query?: {
                /** @description PER-01, MUN-01, MUN-03 o MUN-02 */
                type?: ("person" | "place" | "institution" | "object") | null;
            };
            header?: never;
            path: {
                /** @description Identificador de la novela */
                novel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityList"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["canon__routes__ErrorDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["canon__routes__ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_entity_novels__novel_id__entities__entity_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador de la novela */
                novel_id: string;
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityFile"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["canon__routes__ErrorDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["canon__routes__ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_health_novels__novel_id__health_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador de la novela */
                novel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["supervision__routes__ErrorDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["supervision__routes__ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_retcons_novels__novel_id__retcons_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador de la novela */
                novel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetconList"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["canon__routes__ErrorDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["canon__routes__ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_run_novels__novel_id__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador de la novela */
                novel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunState"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["orchestration__routes__ErrorDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["orchestration__routes__ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_state_novels__novel_id__state_get: {
        parameters: {
            query: {
                /** @description Instante de mundo, ISO 8601 */
                at: string;
                seq?: number;
            };
            header?: never;
            path: {
                /** @description Identificador de la novela */
                novel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorldState"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["canon__routes__ErrorDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["canon__routes__ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_style_novels__novel_id__style_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador de la novela */
                novel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StyleReport"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["verification__routes__ErrorDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["verification__routes__ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trace_novels__novel_id__trace_get: {
        parameters: {
            query?: {
                limit?: number;
                kind?: string | null;
            };
            header?: never;
            path: {
                /** @description Identificador de la novela */
                novel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TracePage"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["orchestration__routes__ErrorDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["orchestration__routes__ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_versions_novels__novel_id__versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador de la novela */
                novel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionList"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["canon__routes__ErrorDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["canon__routes__ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_manifest_novels__novel_id__versions__version__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador de la novela */
                novel_id: string;
                version: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Manifest"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["canon__routes__ErrorDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["canon__routes__ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chapter_at_novels__novel_id__versions__version__chapters__number__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador de la novela */
                novel_id: string;
                version: number;
                number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterAtVersion"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["canon__routes__ErrorDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["canon__routes__ErrorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
